general: 
  outputLevel: debug #options: none, standard, debug

uqMethod:
  type: mlmc
  nMaxIter : 5
  nStochDim: 2
  distribution:
     - uniform: [-1.,1.]
     - normal : [0.,1.]
  nLevels: 4
  # level 1
  levels:
     -nSamples: 100
      currentSamples: 0
      procsPerSample: 1
      avgWalltime: 0
  # level 2
  levels:
     -nSamples: 20
     currentSamples: 0
      procsPerSample: 2
      avgWalltime: 0

machine:
  type: cray

solver:
  type: flexi
