general:
  outputLevel: standard #options: none, standard, debug

uqMethod:
  _type: mlmc
  nMaxIter: 4
  tolerance: 0.1

levels:
   - nCurrentSamples: 10
     nCoresPerSample: 24
     solverPrms:
        nPoints: 10
   - nCurrentSamples: 4
     nCoresPerSample: 48
     solverPrms:
        nPoints: 20
 
stochVars:
- _type: uniform
  bounds: [-1.,1.]
  name: a
- _type: normal
  mean: 1.
  standardDeviation: 0.1
  name: b

machine:
  _type: local
  mpi: false

solver:
  _type: internal
  projectName: v4
  #prmFile: parameter.ini
  exeSimulationPath: ../externals/integration.py
  exePostprocessingPath: ../externals/integrationPostProc.py

