general:
   outputLevel: debug #options: none, standard, debug

uqMethod:
   _type: mlmc
   nMaxIter : 1

levels:
   - nSamples: 10
     nCoresPerSample: 24
     solverPrms:
        MyPrm: 1
   - nSamples: 4
     nCoresPerSample: 48
     solverPrms:
        MyPrm: 2
 
stochVars:
   - _type: uniform
     bounds: [-1.,1.]
     name: a
   - _type: normal
     mean: 1.
     standardDeviation: 0.1
     name: b

machine:
   _type: local

solver:
   _type: internal
   projectName: Integration

