general:
  outputLevel: debug #options: none, standard, debug

uqMethod:
  _type: mlmc
  nMaxIter : 1
  nStochDim: 2
  distribution:
     - uniform: [-1.,1.]
     - normal : [0.,1.]
  nLevels: 2
  levels:
     1:
        nSamples: 10
        nCoresPerSample: 24
     2:
        nSamples: 4
        nCoresPerSample: 48

machine:
  _type: cray

solver:
  _type: flexi

