# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: POUNCE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  basic-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipreqs #flake8 
        pip install -r src/requirements.txt
        #cd src
        #pipreqs --mode no-pin .
        #pip install -r requirements.txt
        #cd ..
    - name: Install external dependencies
      uses: mpi4py/setup-mpi@v1
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r externals/demonstrators/requirements.txt
        #cd externals/demonstrators
        #pipreqs --mode no-pin .
        #python3 -m pip install -r requirements.txt
        #cd ../..
    #- name: Lint with flake8
      #run: |
        ## stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        ## exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: show python version
      run: |
        python --version
        python3 --version
    - name: Test with pytest
      run: |
        mkdir tests 
        cd tests 
        pytest ../src/tests.py
        cd ..
